---
- hosts: all
  become: yes
  tasks:
  - name: Install zabbix-agent on RedHat Family
    yum:
      name: zabbix-agent
      state: latest
    when: ansible_os_family == "RedHat"
    notify: zabbix-agent systemd
  - name: Install zabbix-agent on Ubuntu
    apt:
      name: zabbix-agent
      state: latest
    when: ansible_os_family == "Debian"
    notify: zabbix-agent systemd
  - name: Install script
    template:
      src: /etc/ansible/common/files/zabbix.sh
      dest: /home/smihailov2/zabbix.sh
      mode: '0777'
  handlers:
  - name: zabbix-agent systemd
    systemd:
      name: zabbix-agent.service
      enabled: yes
      state: started

